builds:
  - main: ./cmd/octant-helm
    binary: ./octant-helm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -w

archives:
  -
    id: octant-helm
    format: tar.gz
    files:
      - LICENSE
